env:
  global:
  - VERSION="v$(jq <package.json -r '.version')"
  - GH_BLOB_URL="https://github.com/git9527/anki-persistence/blob/$TRAVIS_COMMIT"
  - GH_SCRIPT_URL="$GH_BLOB_URL/script.js"
language: generic
before_install:
- npm install
install:
- npm install google-closure-compiler
script:
- printf "// $VERSION - $GH_SCRIPT_URL\n$(cat script.js)\n" > script.js
- cat script.js
- 'curl -X POST -s --data-urlencode "input@script.js" https://javascript-minifier.com/raw > minified.js'
- printf "$(head -n 1 script.js)\n$(cat minified.js)\n" > minified.js
- cat minified.js
- npm test
before_deploy:
- git config --local user.name "TravisCI"
- git config --local user.email "travis@travis-ci.org"
- git tag "$VERSION" -a -m "Generated tag by TravisCI build for commit $TRAVIS_COMMIT"
deploy:
  provider: releases
  api_key:
    secure: lYyi5YjCXeNog6i8mAwgCQ
  file:
  - minified.js
  - script.js
  skip_cleanup: true
  name: "$VERSION"
  prerelease: $([ $(echo $VERSION | sed -r -e 's/v([0-9]+).*/\1/') == $(git describe --tags --abbrev=0 | sed -r -e 's/v([0-9]+).*/\1/') ] && printf 'true' || printf 'false') # false if major version changed, true otherwise
  draft: false
  on:
    repo: git9527/anki-persistence
    branch: git9527-release
    condition: $(git describe --tags --abbrev=0) != $VERSION
cache:
  directories:
  - node_modules
